# Configuration

# Book settings
title                       : MSE 590400 Course Website
author                      : Hui-Chia Yu
copyright                   : "2025"
logo                        : Spartan_2.png
only_build_toc_files        : true

# Execution settings
execute:
  execute_notebooks         : 'off'
  allow_errors              : true

# HTML-specific settings
html:
  favicon                   : Spartan_2.png
  use_edit_page_button      : false
  use_repository_button     : false
  use_issues_button         : false
  use_multitoc_numbering    : true
  home_page_in_navbar       : true
  baseurl                   : ""

# LaTeX-specific settings
latex:
  latex_engine              : pdflatex
  use_jupyterbook_latex     : true

# Launch button settings
launch_buttons:
  notebook_interface        : classic
  binderhub_url             : ""
  jupyterhub_url            : "" #https://jupyterhub.egr.msu.edu/
  thebe                     : false
  colab_url                 : "" #https://colab.research.google.com

repository:
  url                       : https://github.com/huichiayu/nthu_mse.github.io
  path_to_book              : .
  branch                    : main

sphinx:
  config:
    html_theme_options:
      launch_buttons: {}
    # suppress_warnings:
    # - myst.header

sass:
  style: compressed

# Add this if you have a custom stylesheet
include:
  - assets/css/styles.css




exclude:
  - references.bib    

